# Generated by Django 2.2.5 on 2019-09-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questin_text',
            new_name='question_text',
        ),
    ]
